import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;
import 'package:flutter_test/flutter_test.dart';
import 'package:nai_launcher/core/constants/api_constants.dart';
import 'package:nai_launcher/core/utils/image_save_utils.dart';
import 'package:nai_launcher/data/models/image/image_params.dart';
import 'package:nai_launcher/data/services/metadata/unified_metadata_parser.dart';

void main() {
  group('ImageSaveUtils metadata semantics', () {
    test('should build metadata from request prompt and explicit preset flags',
        () {
      final params = ImageParams(
        prompt: '1girl, sunset',
        negativePrompt: 'bad hands',
        model: ImageModels.animeDiffusionV45Full,
        qualityToggle: true,
        ucPreset: UcPresets.toApiValue(UcPresetType.heavy),
      );

      final commentJson = ImageSaveUtils.buildCommentJson(
        params: params,
        actualSeed: 123,
        charCaptions: const [
          {
            'char_caption': 'blue dress',
            'centers': [
              {'x': 0.5, 'y': 0.5},
            ],
          },
        ],
        charNegCaptions: const [
          {
            'char_caption': 'extra fingers',
            'centers': [
              {'x': 0.5, 'y': 0.5},
            ],
          },
        ],
      );

      expect(commentJson['prompt'], equals('1girl, sunset'));
      expect(commentJson['uc'], equals('bad hands'));
      expect(commentJson['quality_toggle'], isTrue);
      expect(commentJson['uc_preset'], equals(0));
      expect(commentJson['model'], equals(ImageModels.animeDiffusionV45Full));
      expect(
        commentJson['v4_prompt']['caption']['base_caption'],
        equals('1girl, sunset'),
      );
      expect(
        commentJson['v4_negative_prompt']['caption']['base_caption'],
        equals('bad hands'),
      );

      final metadata = ImageSaveUtils.buildMetadata(
        commentJson: commentJson,
        params: params,
      );
      expect(
        metadata['Description'],
        equals('1girl, sunset'),
      );
    });

    test(
        'should preserve embedded raw png metadata when saving generated bytes',
        () async {
      final png = img.Image(width: 2, height: 2);
      img.fill(png, color: img.ColorRgb8(255, 0, 0));
      var bytes = Uint8List.fromList(img.encodePng(png));

      const rawPrompt = 'artist:a,artist:b';
      const rawNegative = 'nsfw, lowres, bad hands';
      const rawSource = 'NovelAI Diffusion V4.5 4BDE2A90';
      final rawComment = <String, dynamic>{
        'prompt': rawPrompt,
        'uc': rawNegative,
        'seed': 123,
        'width': 2,
        'height': 2,
      };
      bytes = UnifiedMetadataParser.embedTextChunkOnly(
        bytes,
        'Comment',
        '{"prompt":"$rawPrompt","uc":"$rawNegative","seed":123,"width":2,"height":2}',
      );
      bytes = UnifiedMetadataParser.embedTextChunkOnly(
        bytes,
        'Description',
        rawPrompt,
      );
      bytes = UnifiedMetadataParser.embedTextChunkOnly(
        bytes,
        'Software',
        'NovelAI',
      );
      bytes = UnifiedMetadataParser.embedTextChunkOnly(
        bytes,
        'Source',
        rawSource,
      );

      final tempDir = await Directory.systemTemp.createTemp(
        'image_save_utils_test_',
      );
      addTearDown(() async {
        if (await tempDir.exists()) {
          await tempDir.delete(recursive: true);
        }
      });

      final savedFile = await ImageSaveUtils.saveImageWithMetadata(
        imageBytes: bytes,
        filePath: '${tempDir.path}/saved.png',
        params: const ImageParams(
          prompt: 'different prompt',
          negativePrompt: 'different negative',
          model: ImageModels.animeDiffusionV45Full,
        ),
        actualSeed: 456,
      );

      final result = UnifiedMetadataParser.parseFromPng(
        await savedFile.readAsBytes(),
      );

      expect(result.success, isTrue);
      expect(result.metadata, isNotNull);
      expect(result.metadata!.prompt, equals(rawPrompt));
      expect(result.metadata!.negativePrompt, equals(rawNegative));
      expect(result.metadata!.source, equals(rawSource));
      expect(result.metadata!.seed, equals(rawComment['seed']));
    });
  });
}
